### ISSUE TITLE
MuraPlayer

### ISSUE THREAD

**Issue by madebyiando** [stevewithington/MuraPlayer#1]
Hi Steve

I'm running Mura 6.0.5256 for a client and downloaded the MuraPlayer from GitHub. When I create a single page (Page / MuraPlayer) and add a video it works perfectly. However when I setup a "Folder / MuraPlaylist" and add a MuraPlayer page into this folder nothing appears on the folder page. In Mura Admin all the extended attributes appear as they should but in the source code of this 'Folder' page none of the code is created including the JW Player. I watched the MuraShow video step by step but it's still not working. Am I missing something simply?

Cheers

Shaun

**Comment by stevewithington** [comment]
@wiredmonkey, I can't seem to reproduce your issue. could you provide me with additional enviro details such as OS, version, CMFL engine & version, etc.

Also, are you using a YouTube link? If not, what type of video is it?

**Comment by madebyiando** [comment]
Hi Steve

I managed to work out the issue. The previous developer had overwritten the dspBody method which wasn't loading the dsp_portal.cfm or dsp_folder.cfm correctly. I've rectified this and the playlist is now displaying.

Thanks

Shaun

**Comment by stevewithington** [comment]
Thanks for letting me know Shaun.
