### ISSUE TITLE
Not all formats are played

### ISSUE THREAD

**Issue by KillerBeer01** [stevewithington/MuraPlayer#12]
I tried to use MuraPlayer with an uploaded .mp4 file and it worked well, so it did for an .flv file. When I tried to upload a .mov or a .3gp clip, though, the player won't show it, just being stuck at startup (I did several tests, so it's not just the case of a broken clip). In Apache's mime.types, both "mov" and "3gp" are enabled. What else could be wrong?

Thanks.

**Comment by stevewithington** [comment]
The supported file types depend on the type of player you're using, and they're listed on the plugin's index.cfm page (https://github.com/stevewithington/MuraPlayer/blob/551ffa230f34694b70826464989d1fa5de2d600c/index.cfm#L26-L39)  As you'll see, 3GP and MOV files are only supported via the "flash" playback and not the HTML5 playback. Hope that helps!
