### ISSUE TITLE
Embedding into an existing page

### ISSUE THREAD

**Issue by madebyiando** [stevewithington/MuraPlayer#3]
Hi Steve

Is there a way to embed videos into a page using the [mura] tag? I seen your preview video when you added code to the template but unsure whether the mura tag can be used to do this within CKEditor. It's for a non-technical editor.

Cheers as always!

Shaun

**Comment by stevewithington** [comment]
I just pushed fix to allow for this to work properly...now something like this should work:
`[mura]$.muraPlayer.dspJWPlayer(file='/path/to/file.m4v')[/mura]`

You can also specify width and height attributes:
`[mura]$.muraPlayer.dspJWPlayer(file='/path/to/file.m4v', width='480', height='272')[/mura]`

**Comment by stevewithington** [comment]
The fix affected only one file though ... you should be able to update your own file by editing:
**/plugins/MuraPlayer/extensions/components/includes/jwPlayer.cfm**

Around line 120, change this:
`<cfif len(trim(arguments.streamer))>`

To this:
`<cfif len(trim(arguments.streamer)) and arguments.streamer neq 'rtmp:///cfx/st'>`

**Comment by madebyiando** [comment]
Fantastic, thanks for such a quick turnaround, great work!

Shaun

**Comment by madebyiando** [comment]
Works perfectly, thanks again!
