### ISSUE TITLE
[Feature Request] Option for Adding a Video manually to a page.

### ISSUE THREAD

**Issue by davidpanzarella** [stevewithington/MuraPlayer#4]
I know you have this in the code notes "To Do", but have you made any progress on this, or know an easy way to just grab that MuraPlayer() and stuff in an ID to a Mura Player page?

Thanks Steve!

BTW, i'm using a small js script to handle RWD for want to see how it did that.

**Comment by stevewithington** [comment]
You should be able to do `$.muraPlayer.dspJWPlayer(file='/path/to/your/file.ext')`

There's a ton of other arguments that you could pass in as well. The method is found in the file located at https://github.com/stevewithington/MuraPlayer/blob/develop/extensions/components/EventHandler.cfc

**Comment by davidpanzarella** [comment]
Thanks Steve, i'll give that a try!
