### ISSUE TITLE
[Feature - Request] Update to the latest version of JW player?

### ISSUE THREAD

**Issue by Jimcumming** [stevewithington/MuraPlayer#9]
As above

**Comment by sebgmc** [comment]
I second that!

**Comment by stevewithington** [comment]
@Jimcumming & @sebgmc,

The main reason I haven't updated this plugin to the latest version of JWPlayer is that they completely changed their business model after I built this plugin for Mura. Most all of the things that made JWPlayer so compelling to begin with, have been abstracted out and converted to "JWPlayer Plugins" which require you to pay to use many of the features that were free and included with it. I'm now considering the possibility of using a different player altogether.

Thanks,
Steve
